server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: https://eureka-server-cz.herokuapp.com/eureka/
  instance:
    prefer-ip-address: true
    hostname: gateway.herokuapp.com
    homePageUrl: https://${eureka.instance.hostName}/

management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: gateway
spring:
  application:
    name: api-gatewayy
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/api/auth/**
          filters:
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart/**
            - Path=/mylearning/**
            - Path=/api/**
        - id: classRoom-application
          uri: lb://classRoom-application
          predicates:
            - Path=/course/**
        - id: course-service-trainer
          uri: lb://course-service-trainer
          predicates:
            - Path=/course/**
        - id: joboffers-application
          uri: lb://joboffers-application
          predicates:
            - Path=/JobOffers/**
        - id: prehiring-tests-application
          uri: lb://prehiring-tests-application
          predicates:
            - Path=/PrehiringTests/**
        - id: candidateapp-application
          uri: lb://candidateapp-application
          predicates:
            - Path=/CandidateApp/**
        - id: businessauth-application
          uri: lb://businessauth-application
          predicates:
            - Path=/api/auth/**
        - id: skillcourzelo
          uri: lb://skillcourzelo
          predicates:
            - Path=/api/skills/**
            - Path=/skills/**
        - id: quizcourzelo
          uri: lb://quizcourzelo
          predicates:
            - Path=/api/Quiz/**
            - Path=/quiz/**
       