server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: https://eureka-server-courzelo.herokuapp.com/eureka/
  instance:
    prefer-ip-address: true
    hostname: gateway.herokuapp.com
    homePageUrl: https://${eureka.instance.hostName}/

management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: gateway
spring:
  application:
    name: api-gatewayy
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-herokuu
          uri: lb://auth-herokuu
          predicates:
            - Path=/api/auth/**
        - id: business-auth
          uri: lb://business-auth
          predicates:
            - Path=/api/auth/**
            - Path=/websocket-backend/**
            - Path=/socket/**
            - Path=/**
        - id: cart-herokuu
          uri: lb://cart-herokuu
          predicates:
            - Path=/cart/**
            - Path=/mylearning/**
            - Path=/api/**
          filter: 
            - AuthGlobaleFilter
        - id: blog-herokuu
          uri: lb://blog-herokuu
          predicates:
            - Path=/post/**
          filter: 
            - AuthGlobaleFilter
        - id: courzeloclassroom
          uri: lb://courzeloclassroom
          predicates:
            - Path=/api/**
          filter: 
            - AuthGlobaleFilter
        - id: course-service-trainer
          uri: lb://course-service-trainer
          predicates:
            - Path=/course/**
          filter: 
            - AuthGlobaleFilter
        - id: joboffers-application
          uri: lb://joboffers-application
          predicates:
            - Path=/JobOffers/**
          filter: 
            - AuthGlobaleFilter
        - id: prehiring-tests-application
          uri: lb://prehiring-tests-application
          predicates:
            - Path=/PrehiringTests/**
            - Path=/Tests/**
          filter: 
           - AuthGlobaleFilter
        - id: candidateapp-application
          uri: lb://candidateapp-application
          predicates:
            - Path=/CandidateApp/**
          filter: 
            - AuthGlobaleFilter
        - id: skillcourzelo
          uri: lb://skillcourzelo
          predicates:
            - Path=/api/skills/**
            - Path=/skills/**
          filter: 
            - AuthGlobaleFilter
        - id: quizcourzelo
          uri: lb://quizcourzelo
          predicates:
            - Path=/api/**
            - Path=/quiz/**
          filter: 
           - AuthGlobaleFilter
       